# Generated by Django 2.0.3 on 2018-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('o_isim', models.CharField(max_length=50)),
                ('o_soyisim', models.CharField(max_length=50)),
                ('o_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('o_ogretim', models.CharField(choices=[('1.', '1.Öğretim'), ('2.', '2.Öğretim')], max_length=1)),
            ],
        ),
    ]
