# Generated by Django 2.1.3 on 2018-12-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0006_auto_20181209_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konular',
            old_name='title',
            new_name='baslik',
        ),
    ]
