# Generated by Django 2.0.3 on 2018-12-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0009_auto_20181211_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_no',
            field=models.IntegerField(unique=True),
        ),
    ]
