# Generated by Django 2.0.3 on 2018-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0013_auto_20181212_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='ilk_staj',
            field=models.BooleanField(default=True),
        ),
    ]
