# Generated by Django 2.0.3 on 2018-12-14 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0014_ogrenci_ilk_staj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staj',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staj.Ogrenci'),
        ),
    ]
