# Generated by Django 2.0.3 on 2018-12-15 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0015_auto_20181214_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staj',
            name='konu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staj.Konular'),
        ),
    ]
