# Generated by Django 2.0.3 on 2018-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0021_auto_20181217_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulakat',
            name='arkadaslara_davranis',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='İş arkadaşlarına karşı davranış'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='caba_calisma',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Çaba ve Çalışma'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='davranis',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Amire karşı darvranış'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='devam',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Staja Devam'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='isi_vaktinde_tapma',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='İşi vaktinde tamamlama'),
        ),
    ]
