# Generated by Django 2.0.3 on 2018-12-17 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0022_auto_20181217_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulakat',
            name='duzen',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Düzen'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='icerik',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='mulakat_degerlendirmesi',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mülakat'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='proje',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='sunum',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sunum'),
        ),
    ]
