# Generated by Django 2.0.3 on 2018-12-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0028_remove_staj_komisyon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorusme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorusme_tarihi', models.DateField()),
                ('gorusme_saati', models.TimeField()),
                ('gorusme_yapıldı_mı', models.BooleanField(default=False)),
                ('komisyon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staj.Komisyon')),
                ('staj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staj.Staj')),
            ],
        ),
    ]
