# Generated by Django 2.1.3 on 2018-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0029_gorusme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='ilk_staj',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='dgs_veya_yatay_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='onceki_okul',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
