# Generated by Django 2.1.3 on 2018-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0031_auto_20181229_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staj',
            name='baslama_tarihi',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staj',
            name='bitis_tarihi',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staj',
            name='departman_adi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staj',
            name='sehir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
