# Generated by Django 2.1.3 on 2018-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0033_staj_onceki_staj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staj',
            name='onceki_staj',
            field=models.BooleanField(default=False),
        ),
    ]
