# Generated by Django 2.1.3 on 2019-01-01 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0036_ogrenci_ogrenci_dosya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komisyon',
            old_name='uye1',
            new_name='uye1_isim',
        ),
        migrations.RenameField(
            model_name='komisyon',
            old_name='uye2',
            new_name='uye1_soyisim',
        ),
        migrations.AddField(
            model_name='komisyon',
            name='uye2_isim',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='komisyon',
            name='uye2_soyisim',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='staj_gunu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_isim',
            field=models.CharField(max_length=50, verbose_name='Öğrenci Adı'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_no',
            field=models.IntegerField(unique=True, verbose_name='Öğrenci No'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_ogretim',
            field=models.CharField(choices=[('1.', '1'), ('2.', '2')], max_length=2, verbose_name='Öğretim'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_sinif',
            field=models.IntegerField(verbose_name='Sınıfı'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_soyisim',
            field=models.CharField(max_length=50, verbose_name='Öğrenci Soyadı'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_toplam_staj_gunu',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(57)], verbose_name='Toplam Staj Günü'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='ogrenci_dosya',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='staj_tamamadi_mi',
            field=models.BooleanField(default=False, verbose_name='Staj Tamamlandı mı ?'),
        ),
    ]
