# Generated by Django 2.0.3 on 2018-12-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0003_auto_20181110_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_adi', models.CharField(max_length=200)),
                ('sehir', models.CharField(max_length=50)),
                ('baslama_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('ogrenci', models.ForeignKey(on_delete='CASCADE', to='staj.Ogrenci')),
            ],
        ),
    ]
