# Generated by Django 2.0.3 on 2018-12-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0004_staj'),
    ]

    operations = [
        migrations.AddField(
            model_name='staj',
            name='degerlendirildi',
            field=models.BooleanField(default=False),
        ),
    ]
