# Generated by Django 2.1.3 on 2018-12-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0005_staj_degerlendirildi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mulakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulakat_tarhi', models.DateField()),
                ('mulakat_saati', models.TimeField()),
                ('devam', models.IntegerField()),
                ('caba_calisma', models.IntegerField()),
                ('isi_vaktinde_tapma', models.IntegerField()),
                ('davranis', models.IntegerField()),
                ('arkadaslara_davranis', models.IntegerField()),
                ('proje', models.IntegerField()),
                ('duzen', models.IntegerField()),
                ('sunum', models.IntegerField()),
                ('icerik', models.IntegerField()),
                ('mulakat_degerlendirmesi', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='staj',
            name='sinif_durumu',
            field=models.CharField(choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mulakat',
            name='staj',
            field=models.OneToOneField(on_delete='CASCADE', to='staj.Staj'),
        ),
    ]
