# Generated by Django 2.0.3 on 2018-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0007_auto_20181209_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulakat',
            name='caba_calisma',
            field=models.IntegerField(verbose_name='Çaba ve Çalışma'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='devam',
            field=models.IntegerField(verbose_name='Staja Devam'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='isi_vaktinde_tapma',
            field=models.IntegerField(verbose_name='İşi vaktinde tamamlama'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='mulakat_saati',
            field=models.TimeField(verbose_name='Mulakat Saati'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='mulakat_tarhi',
            field=models.DateField(verbose_name='Mulakat Tarihi'),
        ),
    ]
