# Generated by Django 2.0.3 on 2018-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0010_auto_20181211_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='o_sınıf',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
