# Generated by Django 2.0.3 on 2018-12-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0011_ogrenci_o_sınıf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrenci',
            old_name='o_sınıf',
            new_name='o_sinif',
        ),
    ]
