# Generated by Django 2.0.3 on 2018-12-12 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0012_auto_20181211_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='o_toplam_staj_gunu',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(57)]),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='staj_tamamadi_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staj',
            name='departman_adi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staj',
            name='konu',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staj',
            name='toplam_gun',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(15)]),
        ),
    ]
