# Generated by Django 2.1.3 on 2018-12-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0016_auto_20181215_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='konular',
            name='deneme',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
