# Generated by Django 2.0.3 on 2018-12-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0017_konular_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konular',
            name='deneme',
        ),
    ]
