# Generated by Django 2.0.3 on 2018-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0019_staj_staj_sayisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staj',
            name='staj_sayisi',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='staj_sayisi',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
