# Generated by Django 2.0.3 on 2018-12-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0020_auto_20181216_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulakat',
            name='arkadaslara_davranis',
            field=models.IntegerField(choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], verbose_name='İş arkadaşlarına karşı davranış'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='caba_calisma',
            field=models.IntegerField(choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], verbose_name='Çaba ve Çalışma'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='davranis',
            field=models.IntegerField(choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], verbose_name='Amire karşı darvranış'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='devam',
            field=models.IntegerField(choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], verbose_name='Staja Devam'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='duzen',
            field=models.IntegerField(verbose_name='Düzen'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='icerik',
            field=models.IntegerField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='isi_vaktinde_tapma',
            field=models.IntegerField(choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], verbose_name='İşi vaktinde tamamlama'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='mulakat_degerlendirmesi',
            field=models.IntegerField(verbose_name='Mülakat'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='proje',
            field=models.IntegerField(verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='sunum',
            field=models.IntegerField(verbose_name='Sunum'),
        ),
    ]
