# Generated by Django 2.0.3 on 2018-12-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0023_auto_20181217_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mulakat',
            old_name='isi_vaktinde_tapma',
            new_name='isi_vaktinde_yapma',
        ),
    ]
