# Generated by Django 2.0.3 on 2018-12-21 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0025_auto_20181221_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mulakat',
            name='arkadaslara_davranis',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='İş arkadaşlarına karşı davranış'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='caba_calisma',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Çaba ve Çalışma'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='davranis',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Amire karşı darvranış'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='devam',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Staja Devam'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='duzen',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Düzen'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='icerik',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='isi_vaktinde_yapma',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='İşi vaktinde tamamlama'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='mulakat_degerlendirmesi',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mülakat'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='proje',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='mulakat',
            name='sunum',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sunum'),
        ),
    ]
