# Generated by Django 2.0.3 on 2018-12-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0026_auto_20181221_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komisyon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uye1', models.CharField(max_length=200)),
                ('uye2', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='staj',
            name='komisyon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staj.Komisyon'),
        ),
    ]
