# Generated by Django 2.0.3 on 2018-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0027_auto_20181223_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staj',
            name='komisyon',
        ),
    ]
