# Generated by Django 2.1.3 on 2018-12-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0030_auto_20181229_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='onceki_okul',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
