# Generated by Django 2.1.3 on 2018-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0032_auto_20181229_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='staj',
            name='onceki_staj',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
