# Generated by Django 2.1.3 on 2018-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0035_auto_20181229_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='ogrenci_dosya',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
