# Generated by Django 2.1.3 on 2019-01-01 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0037_auto_20190101_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorusme',
            name='gorusme_saati',
            field=models.TimeField(verbose_name='Görüşme Saati'),
        ),
        migrations.AlterField(
            model_name='gorusme',
            name='gorusme_tarihi',
            field=models.DateField(verbose_name='Görüşme Tarihi'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='o_toplam_staj_gunu',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Toplam Staj Günü'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='baslama_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='departman_adi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Departman Adı'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='kurum_adi',
            field=models.CharField(max_length=200, verbose_name='Kurum Adı'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='onceki_staj',
            field=models.BooleanField(default=False, verbose_name='Önceki staj mı ?'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='sehir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='sinif_durumu',
            field=models.CharField(blank=True, choices=[('1,', '1'), ('2,', '2'), ('3,', '3'), ('4,', '4')], max_length=50, null=True, verbose_name='Sınıf Durumu'),
        ),
        migrations.AlterField(
            model_name='staj',
            name='toplam_gun',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Toplam Gün'),
        ),
    ]
