# Generated by Django 2.1.3 on 2019-01-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staj', '0039_staj_gorusme_eklendi_mi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_gun', models.PositiveIntegerField(default=57, verbose_name='Tamamlanması gereken gün sayısı')),
            ],
        ),
    ]
